### ISSUE TITLE
Add an option to ignore a file pattern

### ISSUE THREAD

**Issue by scottchiefbaker** [junegunn/myvim#2]
My vim plugins includes some really big sample files. I'd like to exclude them from myvim, so the file isn't arbitrarily inflated. I've done it manually with `--edit`, but adding an option to the command line would make scripting creating this easier.

**Comment by junegunn** [comment]
I can imagine a few ways to achieve that:
1. Make [this part](https://github.com/junegunn/myvim/blob/master/myvim#L39) of the code configurable
2. Or even the entire find command. This will give maximum flexibility, but it'll be a little harder to use.
3. Optionally `grep -v` after `find` command as you suggested.

**Comment by junegunn** [comment]
I ended up adding `--exclude` option that is interpreted as the argument to `grep -v` command. Try it and let me know if it doesn't work as expected.
