### ISSUE TITLE
Need to use unique names for tempdirs

### ISSUE THREAD

**Issue by scottchiefbaker** [junegunn/myvim#3]
If you run `vim.username` it extracts to `/tmp/myvim/`. If a second user tries to run another instance of myvim it will fail:

```
mkdir: cannot create directory ‘/tmp/myvim/ac588e92’: Permission denied
```

The first user owns the `/tmp/myvim` and the second user isn't allowed to write to that directory.

**Comment by scottchiefbaker** [comment]
Alternately we could append `chmod a+w $MYVIM` to the extract script.

**Comment by junegunn** [comment]
Thanks. Good point. I just changed the base directory to `/tmp/myvim-$(whoami)`.
