### ISSUE TITLE
Add a --permanent option to make config persist

### ISSUE THREAD

**Issue by scottchiefbaker** [junegunn/myvim#4]
On some machines I want the config to persist (i.e. extract to ~/.vim/). Can you add an option to leave the config in place permanently?

**Comment by junegunn** [comment]
Thanks. I added `--hard` option to the generated myvim file for replacing `~/.vim` and `~/.vimrc` on the system, which can be a bit dangerous, so the script keeps backup copies of them. See the code for the details.
