### ISSUE TITLE
Update documentation to include an example of how to exclude multiple files

### ISSUE THREAD

**Issue by scottchiefbaker** [junegunn/myvim#5]
The current documentation says to do `--exclude PATTERN` where pattern is a `grep -v` style pattern for excluding files. I've looked around and I can't make sense of how to exclude two different files/dirs.

Perhaps adding an example to the documentation would help this?

**Comment by junegunn** [comment]
I believe it should be straightforward to the users who have experience with grep which is such a universal tool.

``` sh
(echo $'foo\nbar\nbaz') | grep -v 'foo\|bar'
```

Does this answer your question? And feel free to fork the repository and bend it to your needs, myvim is just a short bash script file that I haven't updated for a while.
